package com.github.wangfeng.procure.common.po.entity.primary;

import com.github.wangfeng.procure.common.po.entity.BaseEntity;
import java.util.Date;
import lombok.Data;

@Data
public class SysConfigDO extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_id
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private Long configId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_name
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private String configName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_key
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private String configKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_value
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private String configValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_type
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private String configType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.create_date
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.create_by
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.update_date
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.update_by
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.remark
     *
     * @mbg.generated Mon Oct 28 16:54:25 CST 2019
     */
    private String remark;

}