package com.github.wangfeng.procure.common.po.entity.primary;

import com.github.wangfeng.procure.common.po.entity.BaseEntity;
import java.util.Date;

public class SysDictTypeDO extends BaseEntity{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type.dict_id
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    private Long dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type.dict_name
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type.dict_type
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type.status
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type.create_date
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type.create_by
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type.update_date
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type.update_by
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_type.remark
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type.dict_id
     *
     * @return the value of sys_dict_type.dict_id
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public Long getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type.dict_id
     *
     * @param dictId the value for sys_dict_type.dict_id
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public void setDictId(Long dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type.dict_name
     *
     * @return the value of sys_dict_type.dict_name
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type.dict_name
     *
     * @param dictName the value for sys_dict_type.dict_name
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type.dict_type
     *
     * @return the value of sys_dict_type.dict_type
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type.dict_type
     *
     * @param dictType the value for sys_dict_type.dict_type
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type.status
     *
     * @return the value of sys_dict_type.status
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type.status
     *
     * @param status the value for sys_dict_type.status
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type.create_date
     *
     * @return the value of sys_dict_type.create_date
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type.create_date
     *
     * @param createDate the value for sys_dict_type.create_date
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type.create_by
     *
     * @return the value of sys_dict_type.create_by
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type.create_by
     *
     * @param createBy the value for sys_dict_type.create_by
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type.update_date
     *
     * @return the value of sys_dict_type.update_date
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type.update_date
     *
     * @param updateDate the value for sys_dict_type.update_date
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type.update_by
     *
     * @return the value of sys_dict_type.update_by
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type.update_by
     *
     * @param updateBy the value for sys_dict_type.update_by
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_type.remark
     *
     * @return the value of sys_dict_type.remark
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_type.remark
     *
     * @param remark the value for sys_dict_type.remark
     *
     * @mbg.generated Tue Oct 29 09:42:03 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}