package com.github.wangfeng.procure.common.po.entity.primary;

import com.github.wangfeng.procure.common.po.entity.BaseEntity;
import java.util.Date;
import lombok.Data;

@Data
public class SysDeptDO extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_id
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private Long deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.parent_id
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.ancestors
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private String ancestors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_name
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.order_num
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.leader
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.phone
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.email
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.status
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.create_date
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.create_by
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.update_date
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.update_by
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.remark
     *
     * @mbg.generated Mon Oct 28 13:27:19 CST 2019
     */
    private String remark;

}