package com.github.wangfeng.procure.common.po.entity.primary;

import com.github.wangfeng.procure.common.annotation.Excel;
import com.github.wangfeng.procure.common.constant.UserConstants;
import com.github.wangfeng.procure.common.po.entity.BaseEntity;
import java.util.Date;
import lombok.Data;

@Data
public class SysDictDataDO extends BaseEntity {

    /** 是否默认（Y是 N否） */
    @Excel(name = "是否默认", readConverterExp = "Y=是,N=否")
    private String isDefault;

    public boolean getDefault()
    {
        return UserConstants.YES.equals(this.isDefault) ? true : false;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_code
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private Long dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_sort
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private Integer dictSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_label
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private String dictLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_value
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.dict_type
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.css_class
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private String cssClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.list_class
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private String listClass;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.status
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.create_date
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.create_by
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.update_date
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.update_by
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict_data.remark
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_code
     *
     * @return the value of sys_dict_data.dict_code
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public Long getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_code
     *
     * @param dictCode the value for sys_dict_data.dict_code
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setDictCode(Long dictCode) {
        this.dictCode = dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_sort
     *
     * @return the value of sys_dict_data.dict_sort
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public Integer getDictSort() {
        return dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_sort
     *
     * @param dictSort the value for sys_dict_data.dict_sort
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setDictSort(Integer dictSort) {
        this.dictSort = dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_label
     *
     * @return the value of sys_dict_data.dict_label
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public String getDictLabel() {
        return dictLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_label
     *
     * @param dictLabel the value for sys_dict_data.dict_label
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setDictLabel(String dictLabel) {
        this.dictLabel = dictLabel == null ? null : dictLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_value
     *
     * @return the value of sys_dict_data.dict_value
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_value
     *
     * @param dictValue the value for sys_dict_data.dict_value
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.dict_type
     *
     * @return the value of sys_dict_data.dict_type
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.dict_type
     *
     * @param dictType the value for sys_dict_data.dict_type
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.css_class
     *
     * @return the value of sys_dict_data.css_class
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public String getCssClass() {
        return cssClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.css_class
     *
     * @param cssClass the value for sys_dict_data.css_class
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setCssClass(String cssClass) {
        this.cssClass = cssClass == null ? null : cssClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.list_class
     *
     * @return the value of sys_dict_data.list_class
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public String getListClass() {
        return listClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.list_class
     *
     * @param listClass the value for sys_dict_data.list_class
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setListClass(String listClass) {
        this.listClass = listClass == null ? null : listClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.is_default
     *
     * @return the value of sys_dict_data.is_default
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.is_default
     *
     * @param isDefault the value for sys_dict_data.is_default
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.status
     *
     * @return the value of sys_dict_data.status
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.status
     *
     * @param status the value for sys_dict_data.status
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.create_date
     *
     * @return the value of sys_dict_data.create_date
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.create_date
     *
     * @param createDate the value for sys_dict_data.create_date
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.create_by
     *
     * @return the value of sys_dict_data.create_by
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.create_by
     *
     * @param createBy the value for sys_dict_data.create_by
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.update_date
     *
     * @return the value of sys_dict_data.update_date
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.update_date
     *
     * @param updateDate the value for sys_dict_data.update_date
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.update_by
     *
     * @return the value of sys_dict_data.update_by
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.update_by
     *
     * @param updateBy the value for sys_dict_data.update_by
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict_data.remark
     *
     * @return the value of sys_dict_data.remark
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict_data.remark
     *
     * @param remark the value for sys_dict_data.remark
     *
     * @mbg.generated Tue Oct 29 09:42:23 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}