package com.github.wangfeng.procure.common.po.entity.primary;

import com.github.wangfeng.procure.common.po.entity.BaseEntity;
import java.util.Date;
import lombok.Data;

@Data
public class SysLogininforDO extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logininfor.info_id
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    private Long infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logininfor.login_name
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logininfor.ipaddr
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    private String ipaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logininfor.login_location
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    private String loginLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logininfor.browser
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logininfor.os
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    private String os;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logininfor.status
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logininfor.msg
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_logininfor.login_time
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logininfor.info_id
     *
     * @return the value of sys_logininfor.info_id
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public Long getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logininfor.info_id
     *
     * @param infoId the value for sys_logininfor.info_id
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public void setInfoId(Long infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logininfor.login_name
     *
     * @return the value of sys_logininfor.login_name
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logininfor.login_name
     *
     * @param loginName the value for sys_logininfor.login_name
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logininfor.ipaddr
     *
     * @return the value of sys_logininfor.ipaddr
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logininfor.ipaddr
     *
     * @param ipaddr the value for sys_logininfor.ipaddr
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr == null ? null : ipaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logininfor.login_location
     *
     * @return the value of sys_logininfor.login_location
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public String getLoginLocation() {
        return loginLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logininfor.login_location
     *
     * @param loginLocation the value for sys_logininfor.login_location
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public void setLoginLocation(String loginLocation) {
        this.loginLocation = loginLocation == null ? null : loginLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logininfor.browser
     *
     * @return the value of sys_logininfor.browser
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logininfor.browser
     *
     * @param browser the value for sys_logininfor.browser
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logininfor.os
     *
     * @return the value of sys_logininfor.os
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logininfor.os
     *
     * @param os the value for sys_logininfor.os
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logininfor.status
     *
     * @return the value of sys_logininfor.status
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logininfor.status
     *
     * @param status the value for sys_logininfor.status
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logininfor.msg
     *
     * @return the value of sys_logininfor.msg
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logininfor.msg
     *
     * @param msg the value for sys_logininfor.msg
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_logininfor.login_time
     *
     * @return the value of sys_logininfor.login_time
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_logininfor.login_time
     *
     * @param loginTime the value for sys_logininfor.login_time
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}