package com.github.wangfeng.procure.common.po.entity.primary;

import com.github.wangfeng.procure.common.po.entity.BaseEntity;
import java.util.Date;
import lombok.Data;

@Data
public class SysPostDO extends BaseEntity {

    /** 用户是否存在此岗位标识 默认不存在 */
    private boolean flag = false;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.post_id
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.post_code
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.post_name
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private String postName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.post_sort
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private Integer postSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.status
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.create_date
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.create_by
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.update_date
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.update_by
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_post.remark
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.post_id
     *
     * @return the value of sys_post.post_id
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.post_id
     *
     * @param postId the value for sys_post.post_id
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.post_code
     *
     * @return the value of sys_post.post_code
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.post_code
     *
     * @param postCode the value for sys_post.post_code
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.post_name
     *
     * @return the value of sys_post.post_name
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.post_name
     *
     * @param postName the value for sys_post.post_name
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setPostName(String postName) {
        this.postName = postName == null ? null : postName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.post_sort
     *
     * @return the value of sys_post.post_sort
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public Integer getPostSort() {
        return postSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.post_sort
     *
     * @param postSort the value for sys_post.post_sort
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setPostSort(Integer postSort) {
        this.postSort = postSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.status
     *
     * @return the value of sys_post.status
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.status
     *
     * @param status the value for sys_post.status
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.create_date
     *
     * @return the value of sys_post.create_date
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.create_date
     *
     * @param createDate the value for sys_post.create_date
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.create_by
     *
     * @return the value of sys_post.create_by
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.create_by
     *
     * @param createBy the value for sys_post.create_by
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.update_date
     *
     * @return the value of sys_post.update_date
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.update_date
     *
     * @param updateDate the value for sys_post.update_date
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.update_by
     *
     * @return the value of sys_post.update_by
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.update_by
     *
     * @param updateBy the value for sys_post.update_by
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_post.remark
     *
     * @return the value of sys_post.remark
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_post.remark
     *
     * @param remark the value for sys_post.remark
     *
     * @mbg.generated Mon Oct 28 16:38:04 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}