package com.github.wangfeng.procure.common.po.entity.primary;

import com.github.wangfeng.procure.common.po.entity.BaseEntity;

public class SysRoleDeptDO extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_dept.role_id
     *
     * @mbg.generated Mon Oct 28 16:12:06 CST 2019
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_dept.dept_id
     *
     * @mbg.generated Mon Oct 28 16:12:06 CST 2019
     */
    private Long deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_dept.role_id
     *
     * @return the value of sys_role_dept.role_id
     *
     * @mbg.generated Mon Oct 28 16:12:06 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_dept.role_id
     *
     * @param roleId the value for sys_role_dept.role_id
     *
     * @mbg.generated Mon Oct 28 16:12:06 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_dept.dept_id
     *
     * @return the value of sys_role_dept.dept_id
     *
     * @mbg.generated Mon Oct 28 16:12:06 CST 2019
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_dept.dept_id
     *
     * @param deptId the value for sys_role_dept.dept_id
     *
     * @mbg.generated Mon Oct 28 16:12:06 CST 2019
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }
}