package com.github.wangfeng.procure.common.po.entity.primary;

import com.github.wangfeng.procure.common.po.entity.BaseEntity;

public class SysUserPostDO extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_post.user_id
     *
     * @mbg.generated Mon Oct 28 16:37:45 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_post.post_id
     *
     * @mbg.generated Mon Oct 28 16:37:45 CST 2019
     */
    private Long postId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_post.user_id
     *
     * @return the value of sys_user_post.user_id
     *
     * @mbg.generated Mon Oct 28 16:37:45 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_post.user_id
     *
     * @param userId the value for sys_user_post.user_id
     *
     * @mbg.generated Mon Oct 28 16:37:45 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_post.post_id
     *
     * @return the value of sys_user_post.post_id
     *
     * @mbg.generated Mon Oct 28 16:37:45 CST 2019
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_post.post_id
     *
     * @param postId the value for sys_user_post.post_id
     *
     * @mbg.generated Mon Oct 28 16:37:45 CST 2019
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }
}