package com.github.wangfeng.procure.common.po.entity.primary;

import com.github.wangfeng.procure.common.po.entity.BaseEntity;
import lombok.Data;

@Data
public class SysUserRoleDO extends BaseEntity {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.user_id
     *
     * @mbg.generated Mon Oct 28 15:57:00 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.role_id
     *
     * @mbg.generated Mon Oct 28 15:57:00 CST 2019
     */
    private Long roleId;

}