package com.github.wangfeng.procure.dao.primary.system;

import com.github.wangfeng.procure.common.po.entity.primary.SysLogininforDO;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SysLogininforMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    int deleteByPrimaryKey(Long infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    int insert(SysLogininforDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    int insertSelective(SysLogininforDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    SysLogininforDO selectByPrimaryKey(Long infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    int updateByPrimaryKeySelective(SysLogininforDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated Mon Oct 28 17:33:07 CST 2019
     */
    int updateByPrimaryKey(SysLogininforDO record);

    /**
     * 新增系统登录日志
     *
     * @param logininfor 访问日志对象
     */
    public void insertLogininfor(SysLogininforDO logininfor);

    /**
     * 查询系统登录日志集合
     *
     * @param logininfor 访问日志对象
     * @return 登录记录集合
     */
    public List<SysLogininforDO> selectLogininforList(SysLogininforDO logininfor);

    /**
     * 批量删除系统登录日志
     *
     * @param ids 需要删除的数据
     * @return 结果
     */
    public int deleteLogininforByIds(String[] ids);

    /**
     * 清空系统登录日志
     *
     * @return 结果
     */
    public int cleanLogininfor();
}