package com.github.wangfeng.procure.dao.primary.system;


import com.github.wangfeng.procure.common.po.entity.primary.SysOperLogDO;
import java.util.List;

public interface SysOperLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated Mon Oct 28 17:54:35 CST 2019
     */
    int deleteByPrimaryKey(Long operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated Mon Oct 28 17:54:35 CST 2019
     */
    int insert(SysOperLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated Mon Oct 28 17:54:35 CST 2019
     */
    int insertSelective(SysOperLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated Mon Oct 28 17:54:35 CST 2019
     */
    SysOperLogDO selectByPrimaryKey(Long operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated Mon Oct 28 17:54:35 CST 2019
     */
    int updateByPrimaryKeySelective(SysOperLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated Mon Oct 28 17:54:35 CST 2019
     */
    int updateByPrimaryKey(SysOperLogDO record);

    /**
     * 新增操作日志
     *
     * @param operLog 操作日志对象
     */
    public void insertOperlog(SysOperLogDO operLog);

    /**
     * 查询系统操作日志集合
     *
     * @param operLog 操作日志对象
     * @return 操作日志集合
     */
    public List<SysOperLogDO> selectOperLogList(SysOperLogDO operLog);

    /**
     * 批量删除系统操作日志
     *
     * @param ids 需要删除的数据
     * @return 结果
     */
    public int deleteOperLogByIds(String[] ids);

    /**
     * 查询操作日志详细
     *
     * @param operId 操作ID
     * @return 操作日志对象
     */
    public SysOperLogDO selectOperLogById(Long operId);

    /**
     * 清空操作日志
     */
    public void cleanOperLog();
}