package com.github.wangfeng.procure.dao.primary.system;

import com.github.wangfeng.procure.common.po.entity.primary.SysUserPostDO;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SysUserPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated Mon Oct 28 16:37:45 CST 2019
     */
    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("postId") Long postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated Mon Oct 28 16:37:45 CST 2019
     */
    int insert(SysUserPostDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated Mon Oct 28 16:37:45 CST 2019
     */
    int insertSelective(SysUserPostDO record);

    /**
     * 通过用户ID删除用户和岗位关联
     *
     * @param userId 用户ID
     * @return 结果
     */
    public int deleteUserPostByUserId(Long userId);

    /**
     * 通过岗位ID查询岗位使用数量
     *
     * @param postId 岗位ID
     * @return 结果
     */
    public int countUserPostById(Long postId);

    /**
     * 批量删除用户和岗位关联
     *
     * @param ids 需要删除的数据ID
     * @return 结果
     */
    public int deleteUserPost(Long[] ids);

    /**
     * 批量新增用户岗位信息
     *
     * @param userPostList 用户角色列表
     * @return 结果
     */
    public int batchUserPost(List<SysUserPostDO> userPostList);
}