package com.github.wangfeng.procure.dao.primary.system;

import com.github.wangfeng.procure.common.po.entity.primary.SysUserOnlineDO;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SysUserOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated Mon Oct 28 17:13:36 CST 2019
     */
    int deleteByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated Mon Oct 28 17:13:36 CST 2019
     */
    int insert(SysUserOnlineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated Mon Oct 28 17:13:36 CST 2019
     */
    int insertSelective(SysUserOnlineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated Mon Oct 28 17:13:36 CST 2019
     */
    SysUserOnlineDO selectByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated Mon Oct 28 17:13:36 CST 2019
     */
    int updateByPrimaryKeySelective(SysUserOnlineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated Mon Oct 28 17:13:36 CST 2019
     */
    int updateByPrimaryKey(SysUserOnlineDO record);

    /**
     * 通过会话序号查询信息
     *
     * @param sessionId 会话ID
     * @return 在线用户信息
     */
    public SysUserOnlineDO selectOnlineById(String sessionId);

    /**
     * 通过会话序号删除信息
     *
     * @param sessionId 会话ID
     * @return 在线用户信息
     */
    public int deleteOnlineById(String sessionId);

    /**
     * 保存会话信息
     *
     * @param online 会话信息
     * @return 结果
     */
    public int saveOnline(SysUserOnlineDO online);

    /**
     * 查询会话集合
     *
     * @param userOnline 会话参数
     * @return 会话集合
     */
    public List<SysUserOnlineDO> selectUserOnlineList(SysUserOnlineDO userOnline);

    /**
     * 查询过期会话集合
     *
     * @param lastAccessTime 过期时间
     * @return 会话集合
     */
    public List<SysUserOnlineDO> selectOnlineByExpired(String lastAccessTime);
}